[project]
name = "openai-agent"
version = "0.1.0"
description = "Fundamental Analyst based on OpenAI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents>=0.3.2",
    "pandas>=2.3.3",
]
